In [44]:
#reshape and trnspose
import numpy as np
a1=np.array([[1,2],[3,4],[4,5]])
a1.shape

(3, 2)

In [45]:
a2=np.array([[1,2,3],[4,5,6]])
a2.shape
a3=a2.reshape(2,3).shape
a1
a3
a1*a3

array([[ 2,  6],
       [ 6, 12],
       [ 8, 15]])

In [46]:
#transpose : switches the axis
a1.shape


(3, 2)

In [47]:
a1.T.shape

(2, 3)

In [48]:
#74 Dot Product vs element wise
np.random.seed(0)
mat1=np.random.randint(10,size=(2,2))
mat2=np.random.randint(10,size=(2,2))



In [49]:
mat1.shape

(2, 2)

In [50]:
mat1

array([[5, 0],
       [3, 3]], dtype=int32)

In [51]:
mat2.shape

(2, 2)

In [52]:
mat2

array([[7, 9],
       [3, 5]], dtype=int32)

In [53]:
mat1 * mat2

array([[35,  0],
       [ 9, 15]], dtype=int32)

In [58]:
#76 Comparision Operators
a1 == a1


array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [ ]:
#77 Sorting Array

In [ ]:
#78 Turn Images Into NumPy Arrays
#turn an image into numpy array